### ISSUE TITLE
hoyolab获取原石摩拉数量不正确

### ISSUE THREAD

**Issue by TheCGDF** [y1ndan/genshinhelper2#15]
Traveler month 1 diary
    💠primogems: 2497
    🌕mora: 2570170
    ##################
原石少了一千多，摩拉多了一百多万

**Comment by y1ndan** [comment]
有没有在其他服务器有账号？核对下角色和摩拉数据对应了么。

**Comment by TheCGDF** [comment]
没其他账户，角色名是对的，账号也正常收到签到奖励了，但是原石和摩拉不对

**Comment by y1ndan** [comment]
暂且标记个bug吧

**Comment by TheCGDF** [comment]
哦突然发现是我理解出问题了。
`Traveler month 1 diary`这段奇怪的英文原来是`旅行札记`的意思啊，我还以为是账户当前的原石和摩拉
但`旅行札记`官方翻译不是`Traveler's Diary : January`么。。。

打扰了，，，
