### ISSUE TITLE
米游社原神每日签到失败

### ISSUE THREAD

**Issue by yawwwwwn** [y1ndan/genshinhelper2#33]
今天的 'https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign' 返回 {'data': None, 'message': 'invalid request', 'retcode': -10001}

但之前的查询账号信息的 'https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn' 的请求是正常返回的，所以 cookie 是没有失效的。

签到过程发生了哪些变化，有没有大佬抓到了。

**Comment by ICMYS** [comment]
抓包看了一下，ds中第二项原本说是100000到200000之间的随机数，现在已经不是单纯数字了，有英文字母在内。
ds更新导致签到和帖子分享/点赞这类post全部invalid request
至于新ds算法只能看大佬逆向了

**Comment by Womsxd** [comment]
https://github.com/Womsxd/AutoMihoyoBBS/blob/master/setting.py#L2-L6
salt和对应的version

**Comment by YzMzx** [comment]
修改salt&version为以下数值
Salt = "dWCcD2FsOUXEstC5f9xubswZxEeoBOTc"
Salt_web = "ulInCDohgEs557j0VsPDYnQaaz6KJcv5"
version = "2.28.1"

**Comment by Womsxd** [comment]
> 修改salt&version为以下数值 Salt = "dWCcD2FsOUXEstC5f9xubswZxEeoBOTc" Salt_web = "ulInCDohgEs557j0VsPDYnQaaz6KJcv5" version = "2.28.1"

已经不需要了，直接用2.34.1的就行了(

**Comment by Myfanqie** [comment]
> 

有用，谢谢大佬
![image](https://user-images.githubusercontent.com/50412437/184673956-8d54593a-0016-4f4f-b9d6-19ffd4413e62.png)

**Comment by MoRanYue** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/1
