### ISSUE TITLE
为什么我按照如下方式去进行配置，但是还是会显示连接不上需要重新登录？

### ISSUE THREAD

**Issue by ZHYCarge** [y1ndan/genshinhelper2#4]
## 图片如下：
![image](https://user-images.githubusercontent.com/40520292/145545573-296a9756-a0d2-47db-a73e-725828994345.png)
以上为代码图片
输出如下：
![image](https://user-images.githubusercontent.com/40520292/145545231-a8ef493d-39f4-47e9-adba-d7038f9e7281.png)
uid以及tocken获取如下：
![image](https://user-images.githubusercontent.com/40520292/145545454-0f159dc5-977a-45b4-8b77-0646969951f5.png)
并且排除过网络问题，更换过网络

**Comment by y1ndan** [comment]
`Genshin()` 函数对应Hoyolab，`YuanShen()` 函数对应米游社 API。

所以要改成`YuanShen`函数。

**Comment by ZHYCarge** [comment]
> 

哇，可以了！谢谢大佬！！！
