### ISSUE TITLE
在新版本中如何启用pushplus推送

### ISSUE THREAD

**Issue by tanxiaofx** [y1ndan/genshinhelper2#40]
之前的PUSH_PLUS_参数已不起作用，官方文档看不懂 求助

**Comment by y1ndan** [comment]
新版统一使用 ONEPUSH 来进行推送

- 默认值：

```json
{
    "notifier": "",
    "params": {
        "markdown": false
    }
}
```

推送相关配置，`notifier`为推送名字，`params`为推送参数。不支持同时使用多个推送。

- bark

```json
ONEPUSH={"notifier":"bark","params":{"markdown":false,"key":"xxxxxx"}}
```

> 注意：如果设置环境变量后报错，可以尝试用单引号包裹变量值，下同。
>
> ```json
> ONEPUSH='{"notifier":"bark","params":{"markdown":false,"key":"xxxxxx"}}'
> ```

- custom

该方式暂时不支持推送签到结果。

- dingtalk

```json
ONEPUSH={"notifier":"dingtalk","params":{"markdown":true,"token":"xxxxxx"}}
```

- discord

```json
ONEPUSH={"notifier":"discord","params":{"markdown":true,"webhook":"https://discord.com/api/webhooks/xxxxxx"}}
```

- pushplus

```json
ONEPUSH={"notifier":"pushplus","params":{"markdown":true,"token":"xxxxxx"}}
```

- qmsg

```json
ONEPUSH={"notifier":"qmsg","params":{"markdown":false,"key":"xxxxxx"}}
```

- serverchan

```json
ONEPUSH={"notifier":"serverchan","params":{"markdown":true,"sckey":"xxxxxx"}}
```

- serverchanturbo

```json
ONEPUSH={"notifier":"serverchanturbo","params":{"markdown":true,"sctkey":"xxxxxx"}}
```

- telegram

```json
ONEPUSH={"notifier":"telegram","params":{"markdown":false,"token":"xxxxxx","userid":"xxxxxx"}}
```

- wechatworkapp

```json
ONEPUSH={"notifier":"wechatworkapp","params":{"markdown":true,"corpid":"xxxxxx","corpsecret":"xxxxxx","agentid":"xxxxxx"}}
```

- wechatworkbot

```json
ONEPUSH={"notifier":"wechatworkbot","params":{"markdown":true,"key":"xxxxxx"}}
```

**Comment by tanxiaofx** [comment]
> 新版统一使用 ONEPUSH 来进行推送
> 
> - 默认值：
> 
> ```json
> {
>     "notifier": "",
>     "params": {
>         "markdown": false
>     }
> }
> ```
> 
> 推送相关配置，`notifier`为推送名字，`params`为推送参数。不支持同时使用多个推送。
> 
> - bark
> 
> ```json
> ONEPUSH={"notifier":"bark","params":{"markdown":false,"key":"xxxxxx"}}
> ```
> 
> > 注意：如果设置环境变量后报错，可以尝试用单引号包裹变量值，下同。
> >
> > ```json
> > ONEPUSH='{"notifier":"bark","params":{"markdown":false,"key":"xxxxxx"}}'
> > ```
> 
> - custom
> 
> 该方式暂时不支持推送签到结果。
> 
> - dingtalk
> 
> ```json
> ONEPUSH={"notifier":"dingtalk","params":{"markdown":true,"token":"xxxxxx"}}
> ```
> 
> - discord
> 
> ```json
> ONEPUSH={"notifier":"discord","params":{"markdown":true,"webhook":"https://discord.com/api/webhooks/xxxxxx"}}
> ```
> 
> - pushplus
> 
> ```json
> ONEPUSH={"notifier":"pushplus","params":{"markdown":true,"token":"xxxxxx"}}
> ```
> 
> - qmsg
> 
> ```json
> ONEPUSH={"notifier":"qmsg","params":{"markdown":false,"key":"xxxxxx"}}
> ```
> 
> - serverchan
> 
> ```json
> ONEPUSH={"notifier":"serverchan","params":{"markdown":true,"sckey":"xxxxxx"}}
> ```
> 
> - serverchanturbo
> 
> ```json
> ONEPUSH={"notifier":"serverchanturbo","params":{"markdown":true,"sctkey":"xxxxxx"}}
> ```
> 
> - telegram
> 
> ```json
> ONEPUSH={"notifier":"telegram","params":{"markdown":false,"token":"xxxxxx","userid":"xxxxxx"}}
> ```
> 
> - wechatworkapp
> 
> ```json
> ONEPUSH={"notifier":"wechatworkapp","params":{"markdown":true,"corpid":"xxxxxx","corpsecret":"xxxxxx","agentid":"xxxxxx"}}
> ```
> 
> - wechatworkbot
> 
> ```json
> ONEPUSH={"notifier":"wechatworkbot","params":{"markdown":true,"key":"xxxxxx"}}
> ```
> 

感谢，已解决
