### ISSUE TITLE
博客上的配置文件模板`config.example.json`已失效

### ISSUE THREAD

**Issue by jqtmviyu** [y1ndan/genshinhelper2#44]
[config.example.json](https://www.yindan.me/tutorial/genshin-impact-helper.html#:~:text=%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%A8%A1%E6%9D%BF-,config.example.json,-%E6%8B%B7%E8%B4%9D%E5%B9%B6%E9%87%8D%E5%91%BD%E5%90%8D)

我进docker 看了下, 应该是: 
```json
{
  "LANGUAGE": "zh",
  "RANDOM_SLEEP_SECS_RANGE": "0-300",
  "CHECK_IN_TIME": "01:00",
  "CHECK_RESIN_SECS": 900,
  "RESIN_THRESHOLD": 150,
  "RESIN_TIMER_DO_NOT_DISTURB": "23:00-07:00",
  "COOKIE_MIHOYOBBS": "account_id=xxx;cookie_token=xxx",
  "COOKIE_RESIN_TIMER": "",
  "COOKIE_BH3": "",
  "COOKIE_MIYOUBI": "",
  "CLOUD_GENSHIN": [
    {
      "x-rpc-combo_token": "",
      "x-rpc-client_type": "",
      "x-rpc-app_version": "",
      "x-rpc-sys_version": "",
      "x-rpc-channel": "",
      "x-rpc-device_id": "",
      "x-rpc-device_name": "",
      "x-rpc-device_model": "",
      "x-rpc-app_id": "",
      "Referer": "https://app.mihoyo.com",
      "Host": "api-cloudgame.mihoyo.com",
      "Connection": "Keep-Alive",
      "Accept-Encoding": "gzip",
      "User-Agent": "okhttp/3.14.9"
    }
  ],
  "COOKIE_HOYOLAB": "",
  "COOKIE_WEIBO": "",
  "COOKIE_KA": "",
  "SHOPTOKEN": "",
  "ONEPUSH": {
    "notifier": "",
    "params": {
      "markdown": false
    }
  }
```

希望能更新下配置参数说明, CLOUD_GENSHIN 这个新增的参数对于用docker的用户很难找到
[配置参数说明](https://www.yindan.me/tutorial/genshin-impact-helper.html#:~:text=%E5%85%A5%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E3%80%82-,%E4%B8%8B%E8%A1%A8%E5%8C%85%E5%90%AB%E4%BA%86%E6%9C%AC%E9%A1%B9%E7%9B%AE%E6%89%80%E7%94%A8%E5%88%B0%E7%9A%84%E5%85%A8%E9%83%A8%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,-%E6%B3%A8%E6%84%8F%EF%BC%9A%E6%9C%89%E7%9A%84)

**Comment by y1ndan** [comment]
现在项目被分成了 3 个小项目：
- genshinhelper2 - 签到相关的封装库，不能开箱即用。
- genshin-checkin-helper - 签到主程序。
- onepush - Push all in One. 一个简单易用的推送包。

配置文件在 genshin-checkin-helper 这个项目里，由于博客教程没有排版，新增的变量在更新部分有说明，格式可以参考配置文件。

**Comment by jqtmviyu** [comment]
> 现在项目被分成了 3 个小项目：
> 
> * genshinhelper2 - 签到相关的封装库，不能开箱即用。
> * genshin-checkin-helper - 签到主程序。
> * onepush - Push all in One. 一个简单易用的推送包。
> 
> 配置文件在 genshin-checkin-helper 这个项目里，由于博客教程没有排版，新增的变量在更新部分有说明，格式可以参考配置文件。

https://gitlab.com/y1ndan/genshin-checkin-helper/-/blob/main/genshincheckinhelper/config/config.example.json
嗯, 确实是我疏忽了, 没去翻gitlab的签到主程序, 希望对遇到相同问题的人有帮助
