### ISSUE TITLE
米氵币签到地址404了

### ISSUE THREAD

**Issue by 2314933036** [y1ndan/genshinhelper2#47]
https://api-takumi.mihoyo.com/apihub/sapi/signIn
这个地址已经404

**Comment by 2314933036** [comment]
https://bbs-api.mihoyo.com/apihub/sapi/signIn
这个地址也是404

**Comment by Womsxd** [comment]
米哈游更换了签到api为: https://bbs-api.mihoyo.com/apihub/app/api/signIn
请求方式为post，提交一个json，内容为{"gids": "签到社区的数字id"}
同时改用新版本ds算法

**Comment by 2314933036** [comment]
> 米哈游更换了签到api为: https://bbs-api.mihoyo.com/apihub/app/api/signIn 请求方式为post，提交一个json，内容为{"gids": "签到社区的数字id"} 同时改用新版本ds算法

我用了 app_version = '2.34.1'
salt = 'z8DRIUjNDT7IT5IZXvrUAxyupA1peND9'
请求你的地址返回的是{"data":null,"message":"invalid request","retcode":-10001}

**Comment by Womsxd** [comment]
> > 米哈游更换了签到api为: https://bbs-api.mihoyo.com/apihub/app/api/signIn 请求方式为post，提交一个json，内容为{"gids": "签到社区的数字id"} 同时改用新版本ds算法
> 
> 我用了 app_version = '2.34.1' salt = 'z8DRIUjNDT7IT5IZXvrUAxyupA1peND9' 请求你的地址返回的是{"data":null,"message":"invalid request","retcode":-10001}

要使用新版本的ds算法

**Comment by 2314933036** [comment]
> > > 米哈游更换了签到api为: https://bbs-api.mihoyo.com/apihub/app/api/signIn 请求方式为post，提交一个json，内容为{"gids": "签到社区的数字id"} 同时改用新版本ds算法
> > 
> > 
> > 我用了 app_version = '2.34.1' salt = 'z8DRIUjNDT7IT5IZXvrUAxyupA1peND9' 请求你的地址返回的是{"data":null,"message":"invalid request","retcode":-10001}
> 
> 要使用新版本的ds算法
我用的这个，要怎么改？
def get_DS():
    t = int(time.time())
    a = "".join(random.sample('abcdefghijklmnopqrstuvwxyz0123456789', 6))
    # ios/安卓验证 x-rpc-client_type=1/2
    b = hashlib.md5(f"salt={salt}&t={t}&r={a}".encode(encoding="utf-8")).hexdigest()
    # 原神签到验证 x-rpc-client_type=5
    # b = hashlib.md5(f"salt=5337810b0c500ace9c4cd745f4b8bcf5&t={t}&r={a}".encode(encoding="utf-8")).hexdigest()
    return f"{t},{a},{b}"

**Comment by Womsxd** [comment]
https://github.com/y1ndan/genshinhelper2/blob/639dfa832bfe00c48f83ba76d32dee337f125eff/genshinhelper/utils.py#L167-L173
这里的即为新版本ds算法

**Comment by 2314933036** [comment]
> https://github.com/y1ndan/genshinhelper2/blob/639dfa832bfe00c48f83ba76d32dee337f125eff/genshinhelper/utils.py#L167-L173
> 
> 
> 这里的即为新版本ds算法

我没理解错的话是要把json（b）和url（q）都传到ds里面对吧

**Comment by Womsxd** [comment]
在签到场景里面的话，我说的是米游币的这个签到，b里面传json，q里面留空，相当于
b={"gids": "11"}&q=

**Comment by 2314933036** [comment]
> 

多谢大佬，那什么时候q会有值呢

**Comment by Womsxd** [comment]
q在get场景下比如 https://bbs-api.mihoyo.com/apihub/app/api/signIn?a=114514&b=1919810的时候q就等于a=114514&b=1919810

**Comment by 2314933036** [comment]
#49
