### ISSUE TITLE
刷新的Cookie

### ISSUE THREAD

**Issue by GOOD-AN** [y1ndan/genshinhelper2#67]
既然使用里面有`stoken`，可不可以在Cookie_token过期的时候，刷新Cookie_token，并将刷新完毕的Cookie_token推送，这样就不用每次过期都去重新登录获取。
请求接口为
`https://api-takumi.mihoyo.com/auth/api/getCookieAccountInfoBySToken`
请求参数为
```json
"uid": "账户ID",
"stoken": "账户stoken"
```
请求方式为`GET`
成功时返回参数为
```json
"retcode": 0,
"message": "OK",
"data": {
    "uid": "账户ID",
    "cookie_token": "新的Cookie_token"
    }
```

**Comment by grinxxoo** [comment]
可行吗？

**Comment by GOOD-AN** [comment]
目前来看，我这边是没有问题的
